# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-29 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wangGiftType', models.CharField(max_length=50, verbose_name=b'\xe5\x9b\x9e\xe7\xa4\xbc\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('getGiftId', models.CharField(max_length=10, null=True, verbose_name=b'\xe5\x9b\x9e\xe7\xa4\xbcID')),
            ],
            options={
                'verbose_name': '\u4e92\u6362\u7ed3\u679c',
                'verbose_name_plural': '\u4e92\u6362\u7ed3\u679c',
                'permissions': (('manager', '\u793c\u7269\u7cfb\u7edf\u7ba1\u7406\u5458'),),
            },
        ),
        migrations.CreateModel(
            name='ExchangeGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aimGroup', models.CharField(choices=[(b'male', '\u7537\u6027'), (b'female', '\u5973\u6027'), (b'both', '\u7537\u5973\u4e0d\u9650')], max_length=6, null=True, verbose_name=b'\xe5\xb8\x8c\xe6\x9c\x9b\xe9\x80\x81\xe7\xbb\x99')),
            ],
            options={
                'verbose_name': '\u53ef\u4e92\u6362\u793c\u7269',
                'verbose_name_plural': '\u53ef\u4e92\u6362\u793c\u7269',
                'permissions': (('manager', '\u793c\u7269\u7cfb\u7edf\u7ba1\u7406\u5458'),),
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftId', models.CharField(max_length=10, null=True, verbose_name=b'\xe7\xa4\xbc\xe7\x89\xa9ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe7\xa4\xbc\xe7\x89\xa9\xe5\x90\x8d')),
                ('type', models.CharField(choices=[(b'01', '\u98df\u7269'), (b'02', '\u670d\u88c5\u914d\u9970'), (b'03', '\u949f\u8868\u9996\u9970'), (b'04', '\u5316\u5986\u54c1'), (b'05', '\u8fd0\u52a8\u6237\u5916'), (b'06', '\u7535\u5668\u6570\u7801'), (b'07', '\u5c0f\u73a9\u610f'), (b'08', '\u624b\u5de5\u7269\u4ef6'), (b'09', '\u4e8c\u6b21\u5143'), (b'10', '\u56fe\u4e66\u97f3\u50cf'), (b'11', '\u5b66\u4e60\u8d44\u6e90'), (b'12', '\u5176\u5b83')], max_length=15, verbose_name=b'\xe7\xa4\xbc\xe7\x89\xa9\xe7\xb1\xbb\xe5\x88\xab')),
                ('description', models.TextField(max_length=1000, verbose_name=b'\xe7\xa4\xbc\xe7\x89\xa9\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('isAnonymous', models.BooleanField(default=False, verbose_name=b'\xe5\x8c\xbf\xe5\x90\x8d')),
                ('isExchange', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe4\xb8\xba\xe4\xba\xa4\xe6\x8d\xa2\xe7\xa4\xbc\xe7\x89\xa9')),
                ('isUsed', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\xb7\xb2\xe5\xae\x8c\xe6\x88\x90\xe4\xba\xa4\xe6\x8d\xa2\xe6\x88\x96\xe8\xb5\xa0\xe4\xb8\x8e')),
            ],
            options={
                'verbose_name': '\u793c\u7269',
                'verbose_name_plural': '\u793c\u7269',
                'permissions': (('manager', '\u793c\u7269\u7cfb\u7edf\u7ba1\u7406\u5458'),),
            },
        ),
        migrations.CreateModel(
            name='GiftSystem_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=10, verbose_name=b'\xe5\xad\xa6\xe5\x8f\xb7')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe5\x90\x8d\xe5\xad\x97')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba')),
                ('area', models.CharField(choices=[(b'C', '\u5357\u533a'), (b'A', '\u897f\u5357'), (b'B', '\u658b\u533a')], default='\u5357\u533a', max_length=1, null=True, verbose_name=b'\xe5\xb1\x85\xe4\xbd\x8f\xe5\x8c\xba\xe5\x9f\x9f')),
                ('wechat', models.CharField(max_length=50, null=True, verbose_name=b'\xe5\xbe\xae\xe4\xbf\xa1\xe5\x8f\xb7')),
            ],
            options={
                'permissions': (('manager', '\u793c\u7269\u7cfb\u7edf\u7ba1\u7406\u5458'),),
            },
        ),
        migrations.CreateModel(
            name='GivenGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenPerson', models.CharField(max_length=100, verbose_name=b'\xe6\x94\xb6\xe7\xa4\xbc\xe8\x80\x85')),
                ('givenPhone', models.CharField(max_length=11, verbose_name=b'\xe6\x94\xb6\xe7\xa4\xbc\xe8\x80\x85\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7')),
                ('givenAdress', models.CharField(max_length=1000, verbose_name=b'\xe6\x94\xb6\xe7\xa4\xbc\xe8\x80\x85\xe5\x85\xb7\xe4\xbd\x93\xe5\x9c\xb0\xe5\x9d\x80')),
                ('gift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='christmas.Gift')),
            ],
            options={
                'verbose_name': '\u88ab\u8d60\u4e88\u793c\u7269',
                'verbose_name_plural': '\u88ab\u8d60\u4e88\u793c\u7269',
                'permissions': (('manager', '\u793c\u7269\u7cfb\u7edf\u7ba1\u7406\u5458'),),
            },
        ),
        migrations.AddField(
            model_name='gift',
            name='own',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='christmas.GiftSystem_user'),
        ),
        migrations.AddField(
            model_name='exchangegift',
            name='gift',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='christmas.Gift'),
        ),
        migrations.AddField(
            model_name='changeresult',
            name='exchangegift',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='christmas.ExchangeGift'),
        ),
    ]
