# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='isGet',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\xb7\xb2\xe6\x94\xb6\xe5\x8f\x96\xe7\xa4\xbc\xe7\x89\xa9'),
        ),
    ]
