# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-06 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0003_auto_20161206_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x88\xa0\xe9\x99\xa4'),
        ),
    ]
