# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-23 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import stucampus.custom.validator
import stucampus.magazine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=40)),
                ('issue', models.IntegerField()),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
                ('pdf_file', models.FileField(upload_to=stucampus.magazine.models.save_path, validators=[stucampus.custom.validator.validate_file])),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
            ],
            options={
                'permissions': (('magazine_add', '\u6dfb\u52a0\u6742\u5fd7'), ('magazine_modify', '\u7f16\u8f91\u6742\u5fd7')),
            },
        ),
    ]
