# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('weekday', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuID', models.CharField(max_length=100)),
            ],
            options={
                'permissions': (('usable', '\u67e5\u770b\u6210\u5458\u7a7a\u95f2\u65f6\u95f4'),),
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='coursetable',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FreeTimeCount.Students'),
        ),
    ]
