# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-23 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('organization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
            options={
                'permissions': (('infors_list', 'List all informations'), ('infor_show', 'Show an informations'), ('infor_create', 'Create an information'), ('infor_edit', 'Edit an information'), ('infor_del', 'Delete an information')),
            },
        ),
    ]
