# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-22 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('cover', models.ImageField(max_length=200, upload_to=b'')),
                ('describe', models.CharField(max_length=64)),
                ('jumpUrl', models.URLField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=5, verbose_name='\u4f18\u5148\u7ea7')),
                ('published', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('createDate', models.DateField(auto_now_add=True)),
                ('lastModify', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='\u6700\u540e\u4fee\u6539\u8005')),
            ],
            options={
                'permissions': (('slide_add', '\u9996\u9875\u7126\u70b9\u56fe\u6dfb\u52a0'), ('slide_manage', '\u9996\u9875\u7126\u70b9\u56fe\u7ba1\u7406')),
            },
        ),
    ]
