# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-07 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('summer_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 7, 12, 40, 24, 307260, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
