# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_plans', '0002_plan_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='szu_ic',
            field=models.CharField(default=130254, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='szu_org_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='szu_sex',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='szu_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
