# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_plans', '0002_auto_20160610_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_color',
            field=models.IntegerField(blank=True, choices=[(1, '#A0C1E5'), (2, '#DAE5A0'), (3, '#E5A1A0'), (4, '#D6A0E5'), (5, '#506B90')], max_length=1, null=True),
        ),
    ]
