# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_plans', '0004_auto_20160611_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alias',
            field=models.CharField(blank=True, default='\u533f\u540d', max_length=10, null=True, verbose_name='\u533f\u540d\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_color',
            field=models.IntegerField(choices=[(1, '#A0C1E5'), (2, '#DAE5A0'), (3, '#E5A1A0'), (4, '#D6A0E5'), (5, '#506B90')], default=1),
        ),
    ]
