# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-12 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summer_plans', '0007_auto_20160612_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='\u8bb0\u5f55\u7684\u5185\u5bb9')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='summer_plans.Plan')),
            ],
        ),
    ]
