# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-12 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summer_plans', '0008_planrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planrecord',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_record', to='summer_plans.Plan'),
        ),
    ]
