# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-12 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summer_plans', '0009_auto_20160612_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrecord',
            name='deleted',
        ),
    ]
