# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-15 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_plans', '0011_lottery_lotterylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotterylist',
            name='draw_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u5f00\u542f\u62bd\u5956\u7684\u65f6\u95f4'),
        ),
    ]
