# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-15 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_plans', '0012_lotterylist_draw_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotterylist',
            old_name='draw_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='lotterylist',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u5173\u95ed\u62bd\u5956\u7684\u65f6\u95f4'),
        ),
    ]
