# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-15 09:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('summer_plans', '0013_auto_20160615_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterylist',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 15, 9, 17, 33, 249220, tzinfo=utc), verbose_name='\u5173\u95ed\u62bd\u5956\u7684\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lotterylist',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 15, 9, 17, 42, 997610, tzinfo=utc), verbose_name='\u5f00\u542f\u62bd\u5956\u7684\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
