# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-15 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summer_plans', '0014_auto_20160615_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterylist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_list', to='summer_plans.PlanCategory'),
        ),
    ]
