# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_plans', '0015_auto_20160615_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
