# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-17 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100, verbose_name='\u8054\u7cfb\u4eba')),
                ('content', models.TextField(max_length=10000, verbose_name='\u53cd\u9988\u5185\u5bb9')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': '\u53cd\u9988',
                'verbose_name_plural': '\u53cd\u9988',
            },
        ),
    ]
