# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-17 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gobye', '0002_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': '\u53cd\u9988', 'verbose_name_plural': '\u53cd\u9988'},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
    ]
