# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('mobile_phone_number', models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7')),
                ('szu_no', models.CharField(max_length=10, verbose_name='\u5b66\u53f7')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('member_add', '\u901a\u8baf\u5f55\u4eba\u5458\u6dfb\u52a0'), ('member_manage', '\u901a\u8baf\u5f55\u4eba\u5458\u7ba1\u7406')),
            },
        ),
    ]
