# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-27 09:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member_infor', '0002_auto_20160527_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 5, 27, 9, 2, 45, 98146, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
