# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-28 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_infor', '0005_auto_20160528_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5'),
        ),
        migrations.AlterField(
            model_name='member',
            name='nick_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u7ef0\u53f7'),
        ),
    ]
