# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-15 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(verbose_name=b'\xe5\x85\xac\xe6\x96\x87\xe9\x80\x9a\xe7\xbc\x96\xe5\x8f\xb7')),
                ('type', models.CharField(max_length=10, verbose_name=b'\xe7\xb1\xbb\xe5\x88\xab')),
                ('unit', models.CharField(max_length=20, verbose_name=b'\xe5\x8f\x91\xe6\x96\x87\xe5\x8d\x95\xe4\xbd\x8d')),
                ('title', models.CharField(max_length=100, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98')),
                ('date', models.DateField(verbose_name=b'\xe6\x97\xa5\xe6\x9c\x9f')),
                ('content', models.CharField(max_length=10000, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('isShow', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\xb1\x95\xe7\xa4\xba')),
                ('isTop', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe7\xbd\xae\xe9\xa1\xb6')),
                ('hasFile', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x9c\x89\xe9\x99\x84\xe4\xbb\xb6')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': '\u6807\u9898',
                'verbose_name_plural': '\u6807\u9898',
                'permissions': (('manager', '\u516c\u6587\u901a\u4fe1\u606f\u7ba1\u7406\u5458'),),
            },
        ),
    ]
