# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('\u4e0a\u5348', '\u4e0a\u5348'), ('\u4e0b\u5348', '\u4e0b\u5348')], max_length=10)),
                ('specific_time', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=140)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
