# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-12 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import stucampus.minivideo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_captain', models.CharField(max_length=20)),
                ('team_captain_phone', models.CharField(max_length=30)),
                ('team_captain_stuno', models.CharField(max_length=10)),
                ('team_captain_college', models.CharField(max_length=30)),
                ('team_members1_name', models.CharField(blank=True, max_length=20)),
                ('team_members1_id', models.CharField(blank=True, max_length=10)),
                ('team_members2_name', models.CharField(blank=True, max_length=20)),
                ('team_members2_id', models.CharField(blank=True, max_length=10)),
                ('team_members3_name', models.CharField(blank=True, max_length=20)),
                ('team_members3_id', models.CharField(blank=True, max_length=10)),
                ('team_members4_name', models.CharField(blank=True, max_length=20)),
                ('team_members4_id', models.CharField(blank=True, max_length=10)),
                ('team_members5_name', models.CharField(blank=True, max_length=20)),
                ('team_members5_id', models.CharField(blank=True, max_length=10)),
                ('team_psw', models.CharField(max_length=30)),
                ('video_cover', models.ImageField(upload_to=stucampus.minivideo.models.save_path)),
                ('video_name', models.CharField(max_length=50)),
                ('video_intro', models.CharField(max_length=200)),
                ('video_link', models.URLField(max_length=300)),
                ('votes', models.IntegerField(default=0)),
                ('has_verified', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('manager', '\u5fae\u89c6\u5927\u8d5b\u7ba1\u7406\u5458'),),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=20)),
                ('stu_ic', models.CharField(max_length=10)),
                ('voted_id', models.CharField(max_length=3)),
            ],
        ),
    ]
