# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-22 17:52
from __future__ import unicode_literals

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('summary', models.CharField(max_length=50)),
                ('content', DjangoUeditor.models.UEditorField()),
                ('author', models.CharField(max_length=30)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('source_link', models.URLField(blank=True, null=True)),
                ('cover', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('create_ip', models.GenericIPAddressField(editable=False, null=True)),
                ('click_count', models.IntegerField(default=0, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('article_add', '\u6dfb\u52a0\u6587\u7ae0'), ('article_manage', '\u7f16\u5ba1\u6587\u7ae0')),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u5206\u7c7b\u540d')),
                ('english_name', models.CharField(max_length=20, unique=True)),
                ('priority', models.PositiveIntegerField(verbose_name='\u4f18\u5148\u7ea7')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
