# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-15 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20160325_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default=b'festival_20160415233002_137.jpg', upload_to=b''),
        ),
    ]
