# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-15 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160415_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
