# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-15 18:07
from __future__ import unicode_literals

from django.db import migrations
import stucampus.custom.model_field


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20160416_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=stucampus.custom.model_field.QiniuUEditorField(),
        ),
    ]
