# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-16 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20160416_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
