# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-16 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20160416_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default=b'dfsdf.jpg', upload_to=b''),
        ),
    ]
