# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-24 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20160416_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default=b'dfsdf.jpg', max_length=200, upload_to=b''),
        ),
    ]
