# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-25 15:46
from __future__ import unicode_literals

from django.db import migrations
import stucampus.custom.model_field


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20160424_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=stucampus.custom.model_field.QiniuImageField(default=b'default_cover.png', max_length=200, upload_to=b''),
        ),
    ]
