# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-30 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[(b'male', '\u7537'), (b'female', '\u5973')], default=b'male', max_length=6)),
                ('stu_ID', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=11)),
                ('dept1', models.CharField(choices=[(b'xzb', '\u884c\u653f\u90e8'), (b'sjb', '\u8bbe\u8ba1\u90e8'), (b'jsb', '\u6280\u672f\u90e8'), (b'cbb', '\u91c7\u7f16\u90e8'), (b'yyb', '\u8fd0\u8425\u90e8')], default=b'cbb', max_length=4)),
                ('dept2', models.CharField(choices=[(b'xzb', '\u884c\u653f\u90e8'), (b'sjb', '\u8bbe\u8ba1\u90e8'), (b'jsb', '\u6280\u672f\u90e8'), (b'cbb', '\u91c7\u7f16\u90e8'), (b'yyb', '\u8fd0\u8425\u90e8')], default=b'jsb', max_length=4)),
                ('ip', models.GenericIPAddressField()),
                ('sign_up_date', models.DateField(auto_now_add=True)),
                ('self_intro', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'permissions': (('manager', '\u62a5\u540d\u4fe1\u606f\u7ba1\u7406\u5458'),),
            },
        ),
    ]
