# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-31 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='register',
            name='status',
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='grade',
            field=models.CharField(default=2014, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='dept2',
            field=models.CharField(blank=True, choices=[(b'xzb', '\u884c\u653f\u90e8'), (b'sjb', '\u8bbe\u8ba1\u90e8'), (b'jsb', '\u6280\u672f\u90e8'), (b'cbb', '\u91c7\u7f16\u90e8'), (b'yyb', '\u8fd0\u8425\u90e8')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='self_intro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
