# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-09-09 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamer', '0003_auto_20160910_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='college',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'\xe5\xad\xa6\xe9\x99\xa2'),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'male', '\u7537'), (b'female', '\u5973')], default=b'male', max_length=6, null=True, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab'),
        ),
        migrations.AlterField(
            model_name='register',
            name='grade',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name=b'\xe5\xb9\xb4\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba'),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='register',
            name='stu_ID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe5\xad\xa6\xe5\x8f\xb7'),
        ),
    ]
