# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import stucampus.szuspeech.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_title', models.CharField(max_length=50)),
                ('resource_intro', models.CharField(max_length=200)),
                ('uploaded_file', models.FileField(upload_to=stucampus.szuspeech.models.save_path)),
                ('is_preview', models.BooleanField(default=False)),
                ('preview1', models.ImageField(blank=True, upload_to=stucampus.szuspeech.models.preview_pic_save_path)),
                ('preview2', models.ImageField(blank=True, upload_to=stucampus.szuspeech.models.preview_pic_save_path)),
                ('preview3', models.ImageField(blank=True, upload_to=stucampus.szuspeech.models.preview_pic_save_path)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('is_top', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('manager', '\u6df1\u5927\u6f14\u8bb2\u7ba1\u7406\u5458'),),
            },
        ),
    ]
