# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('keyword', models.CharField(help_text='\u7528\u6237\u53d1\u51fa\u7684\u5173\u952e\u8bcd', max_length=256, primary_key=True, serialize=False, verbose_name='\u5173\u952e\u8bcd')),
                ('content', models.TextField(blank=True, help_text='\u56de\u590d\u7ed9\u7528\u6237\u7684\u5185\u5bb9', null=True, verbose_name='\u5185\u5bb9')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('published', models.BooleanField(default=True, verbose_name='\u53d1\u5e03\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u5173\u952e\u8bcd',
                'verbose_name_plural': '\u5173\u952e\u8bcd',
            },
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(max_length=256, verbose_name='\u5fae\u4fe1\u8bc6\u522b\u7801')),
                ('lottery_id', models.CharField(max_length=16, verbose_name='\u62bd\u5956\u7f16\u53f7')),
                ('isUseful', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6709\u6548')),
            ],
        ),
    ]
