# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-08 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='pic_url',
            field=models.URLField(blank=True, null=True, verbose_name='\u56fe\u7247\u94fe\u63a5'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='reply_type',
            field=models.CharField(choices=[('1', '\u6587\u5b57\u56de\u590d'), ('2', '\u56fe\u6587\u56de\u590d')], default='1', max_length=1, verbose_name='\u56de\u590d\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u6807\u9898'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='to_url',
            field=models.URLField(blank=True, null=True, verbose_name='\u8df3\u8f6c\u94fe\u63a5'),
        ),
    ]
